use std::fs;
use std::path::PathBuf;

/// 默认语言：协商与路径兜底全落空时的落点；须存在于 locales/ 中（generate_i18n 断言）
const DEFAULT_LOCALE: &str = "en";

fn main() {
    println!("cargo::rerun-if-changed=src");
    println!("cargo::rerun-if-changed=public/styles.css");

    // 网络受限环境可经 TAILWIND_CLI 环境变量指定本地 CLI，跳过 GitHub 下载
    let mut tailwind = topcoat::tailwind::BuildConfig::new();
    if std::env::var_os("TAILWIND_CLI").is_some() {
        tailwind = tailwind.executable_env("TAILWIND_CLI");
    }
    tailwind.input("public/styles.css").render().unwrap();

    // 图标集走项目内缓存目录（离线可复现构建）
    topcoat::icon::iconify::BuildConfig::new()
        .icon_set("mdi")
        .cache_dir(".topcoat-cache/iconify")
        .stage()
        .unwrap();

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    generate_i18n(&out);
}

fn generate_i18n(out: &PathBuf) {
    let locales_dir = PathBuf::from("locales");
    println!("cargo::rerun-if-changed={}", locales_dir.display());

    // 语言码统一经 ICU 解析 + 规范化（compiled_data），文件名非法时构建直接失败
    let canonicalizer = icu::locale::LocaleCanonicalizer::new_common();
    let mut locales: Vec<(String, String)> = fs::read_dir(&locales_dir)
        .expect("locales 目录不存在")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map_or(false, |ext| ext == "json"))
        .filter_map(|p| {
            let code = p.file_stem()?.to_str()?.to_string();
            let json = fs::read_to_string(&p).ok()?;
            let mut locale = icu::locale::Locale::try_from_str(&code)
                .unwrap_or_else(|e| panic!("locales/{code}.json 文件名不是合法 BCP47 语言标识: {e}"));
            canonicalizer.canonicalize(&mut locale);
            Some((locale.to_string(), json))
        })
        .collect();
    locales.sort();
    assert!(
        !locales.is_empty(),
        "locales/ 目录中未找到任何 .json 语言文件"
    );
    assert!(
        locales.iter().any(|(loc, _)| loc == DEFAULT_LOCALE),
        "DEFAULT_LOCALE \"{DEFAULT_LOCALE}\" 不在 locales/ 目录中"
    );

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED BY build.rs\n");
    code.push_str("use std::collections::HashMap;\n");
    code.push_str("use std::sync::LazyLock;\n\n");
    code.push_str("fn load_locale(json: &str) -> HashMap<&'static str, &'static str> {\n");
    code.push_str("    let raw: HashMap<String, String> = serde_json::from_str(json).unwrap();\n");
    code.push_str("    raw.into_iter()\n");
    code.push_str("        .map(|(k, v)| (Box::leak(k.into_boxed_str()) as &str, Box::leak(v.into_boxed_str()) as &str))\n");
    code.push_str("        .collect()\n");
    code.push_str("}\n\n");

    code.push_str(
        "static LOCALES: LazyLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =\n",
    );
    code.push_str("    LazyLock::new(|| {\n");
    code.push_str("        let mut m = HashMap::new();\n");
    for (loc, json) in &locales {
        code.push_str(&format!(
            "        m.insert(\"{loc}\", load_locale(r###\"{json}\"###));\n"
        ));
    }
    code.push_str("        m\n");
    code.push_str("    });\n\n");

    code.push_str(&format!(
        "pub const DEFAULT_LOCALE: &str = \"{}\";\n",
        DEFAULT_LOCALE
    ));
    code.push_str(&format!(
        "pub const SUPPORTED: &[&str] = &[{}];\n",
        locales
            .iter()
            .map(|l| format!("\"{}\"", l.0))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    code.push_str("pub fn is_supported(locale: &str) -> bool { LOCALES.contains_key(locale) }\n\n");

    code.push_str("pub fn t<'a>(locale: &str, key: &'a str) -> &'a str {\n");
    code.push_str("    LOCALES.get(locale)\n");
    code.push_str("        .or_else(|| LOCALES.get(DEFAULT_LOCALE))\n");
    code.push_str("        .and_then(|m| m.get(key).copied())\n");
    code.push_str("        .unwrap_or(key)\n");
    code.push_str("}\n");

    fs::write(out.join("i18n_gen.rs"), code).unwrap();
}
